### ISSUE TITLE
Empty csv annotations

### ISSUE THREAD

**Issue by parkersell** [CaptainCook4D/annotations#1]
Hi @rohithpeddi and @Error-Dataset,

I was looking to work on this dataset and on this task. However, I found that the csv files found at https://github.com/Error-Dataset/annotations/blob/main/videos/combined/step_annotations.csv are empty. So far I have found the annotated taskgraphs that were made for the task. However, I have not found any labels for the error task or any step level segmentation. 

Could you please assist me in finding these annotations so I can begin working on this task? 

Thanks, 
Parker Sell
parkersell27@gmail.com

**Comment by rohithpeddi** [comment]
Annotations for both steps and errors are updated.
