### ISSUE TITLE
Baselines

### ISSUE THREAD

**Issue by olga-zats** [CaptainCook4D/annotations#2]
Hi @rohithpeddi and @CaptainCook4D ,

thank you for your interesting work! I wonder if you are planning to release the pre-trained baselines for the benchmarks? That would be very helpful!

Best,
Olga

**Comment by CaptainCook4D** [comment]
Hi @olga-zats,

We have released the feature extraction scripts and the corresponding extracted features used in our baselines. 
Please check here: [Feature Extractors](https://github.com/CaptainCook4D/feature_extractors)

We have released **under development** code used for baselines. (We shall release final version in a few weeks)
Please check here: 

1. [Multi-Step Localization](https://github.com/CaptainCook4D/multi_step_localization)
2. [Error Recognition](https://github.com/CaptainCook4D/error_recognition)
