### ISSUE TITLE
What's difference between complete_step_annotations.json, error_annotations.json, and step_annotations.json?

### ISSUE THREAD

**Issue by Y-Haneji** [CaptainCook4D/annotations#3]
@rohithpeddi 
Thank you for the great publication!

The directory `annotation_json` has three files mentioned in the title. How can I use them properly?

**Comment by rohithpeddi** [comment]
Hi @Y-Haneji, 

Thank you for your interest in our work. 
We have added a new file which describes the released annotations. 

Please have a look at this file: [ANNOTATIONS.md](https://github.com/CaptainCook4D/annotations/blob/main/ANNOTATIONS.md)

**Comment by Y-Haneji** [comment]
@rohithpeddi 
Thank you for your information!
I've understood the data structure.
