### ISSUE TITLE
Fine-grained Action Annotations

### ISSUE THREAD

**Issue by 594zyc** [CaptainCook4D/annotations#4]
Hi, 

First of all, thanks for releasing such a great dataset! It seems that the 10K fine-grained action annotations mentioned in the paper are not included in the repo. Is there a plan to release them as well? Thanks

**Comment by rohithpeddi** [comment]
@594zyc 

Thank you for your interest in our work. 
Yes, we shall release the 10K annotations as well in a few weeks.
